version: '3.6'

services:
    bot:
        build: .
        env_file: .env
        depends_on: 
            - redis
            - mysql

    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes", "--port", "5432"]
        hostname: redis
        volumes:
            - ./storage/redis/data:/data
        
    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes: 
            - ./storage/mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
